# Site settings
baseurl: "/content"
url: "http://ms-iot.github.io/content"
repositoryurl: "https://github.com/ms-iot/content/blob/develop/"
msiotorgurl: "https://github.com/ms-iot"
landingurl: "http://go.microsoft.com/fwlink/p/?LinkID=534186"
hacksterurl: "http://microsoft.hackster.io"
hardwareurl: "http://go.microsoft.com/fwlink/p/?linkID=532948"
signupurl: "https://www.windowsondevices.com/signup.aspx"
downloadurl: "http://connect.microsoft.com/windowsembeddedIoT/Downloads/"
sampleurl: "https://github.com/ms-iot/samples"
iotexturl: "/windows/iot"
exclude: ["Resources/contribute/"]


# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink: pretty
highlighter: rouge 
safe: false
lsi: false

defaults:
  - # Site global default(s)
    scope:
      path: "" # Files under site root
      type: "pages" # Only files of type page
    values:
      search_product: "eADQiWindows 10XVcnh"
      layout: "default"
  - # en-US-specific default(s)
    scope:
      path: "en-US" # Files under en-US folder
      type: "pages" # Only files of type page
    values:
      lang: "en-US"
  - # zh-cn-specific default(s)
    scope:
      path: "zh-CN" # Files under zh-CN folder
      type: "pages" # Only files of type page
    values:
      lang: "zh-CN"
